[jobs.auto-install]
command = ["cargo", "install", "--path", ".", "--locked"]
need_stdout = true
allow_warnings = true
background = true

[jobs.run-install]
command = ["cargo", "run", "--", "install"]
need_stdout = true
allow_warnings = true
background = true

[jobs.run-load]
command = ["cargo", "run", "--", "load"]
need_stdout = true
allow_warnings = true
background = true

[jobs.run-clean-install]
command = [
    "bash",
    "-c",
    "rm -rf ~/.local/share/tmux/plugins; cargo run -- install",
]
need_stdout = true
allow_warnings = true
background = true
before = []
