quoted_string = _{ SOI ~ (single_quoted | double_quoted) ~ (whitespace* ~ line_comment)? ~ EOI }

single_quoted = _{ "'" ~ single_inner ~ "'" }
single_inner  = @{ (!"'" ~ ANY)* }

double_quoted = _{ "\"" ~ double_inner ~ "\"" }
double_inner  = @{ (escaped_char | normal_char)* }

escaped_char = { "\\" ~ ("\"" | "\\") }
normal_char  = { !("\\" | "\"") ~ ANY }

whitespace   = _{ " " | "\t" }
line_comment = _{ "#" ~ ANY* }
